# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Consulta Cidadã - Confiança no Legislativo
email: contato@cidadaniainteligente.org
description: > # this means to ignore newlines until "baseurl:"
  A Fundação Cidadania Inteligente está apoiando a Rede Latino-Americana pela Transparência Legislativa (RLTL) 
  em sua primeira ação no Brasil, 
  que é parte do processo de reestruturação e planejamento estratégico da Rede.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://br.transparencialegislativa.org" # the base hostname & protocol for your site
twitter_username: ciudadanoi
github_username:  ciudadanointeligente

# Build settings
markdown: kramdown

#OGP
ogp_title: Consulta Cidadã - Confiança no Legislativo
ogp_type: website
ogp_url:
ogp_image:
ogp_description: >
  A Fundação Cidadania Inteligente está apoiando a Rede Latino-Americana pela Transparência Legislativa (RLTL) 
  em sua primeira ação no Brasil, 
  que é parte do processo de reestruturação e planejamento estratégico da Rede.
#Twitter
tw_card: summary
tw_site: "https://br.transparencialegislativa.org"
tw_title: Consulta Cidadã - Confiança no Legislativo
tw_description: >
  A Fundação Cidadania Inteligente está apoiando a Rede Latino-Americana pela Transparência Legislativa (RLTL) 
  em sua primeira ação no Brasil, 
  que é parte do processo de reestruturação e planejamento estratégico da Rede.
tw_creator:
tw_image:

google-analytics: 'UA-41822715-15'

#browsers
chrome-theme-color: '#000000'
safari-theme-color: '#000000'
